//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 康家_藥物疾病列表
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbClassEntities : DbContext
    {
        public dbClassEntities()
            : base("name=dbClassEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Consultation> Consultation { get; set; }
        public virtual DbSet<CounsultTypeRecord> CounsultTypeRecord { get; set; }
        public virtual DbSet<EmergenceCaller> EmergenceCaller { get; set; }
        public virtual DbSet<PatientInfo> PatientInfo { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tClassThemeList> tClassThemeList { get; set; }
        public virtual DbSet<tEventType> tEventType { get; set; }
        public virtual DbSet<tFunctionBrige> tFunctionBrige { get; set; }
        public virtual DbSet<tGroupActivity> tGroupActivity { get; set; }
        public virtual DbSet<tGroupActivityClassTheme> tGroupActivityClassTheme { get; set; }
        public virtual DbSet<tGroupActivityPicAndFiles> tGroupActivityPicAndFiles { get; set; }
        public virtual DbSet<tPersonalPerformance> tPersonalPerformance { get; set; }
        public virtual DbSet<tScheduleDetails> tScheduleDetails { get; set; }
        public virtual DbSet<TypeNames> TypeNames { get; set; }
        public virtual DbSet<功能評估> 功能評估 { get; set; }
        public virtual DbSet<功能評估個表> 功能評估個表 { get; set; }
        public virtual DbSet<疾病診斷> 疾病診斷 { get; set; }
        public virtual DbSet<疾病總表> 疾病總表 { get; set; }
        public virtual DbSet<病人用藥資訊> 病人用藥資訊 { get; set; }
        public virtual DbSet<病人開藥日期> 病人開藥日期 { get; set; }
        public virtual DbSet<復健計畫> 復健計畫 { get; set; }
        public virtual DbSet<藥物使用方法> 藥物使用方法 { get; set; }
        public virtual DbSet<藥物服用時間> 藥物服用時間 { get; set; }
        public virtual DbSet<藥物計量單位> 藥物計量單位 { get; set; }
        public virtual DbSet<藥物資訊清單> 藥物資訊清單 { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Rank> Rank { get; set; }
    }
}
