//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 康家_藥物疾病列表
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientInfo()
        {
            this.EmergenceCaller = new HashSet<EmergenceCaller>();
            this.功能評估 = new HashSet<功能評估>();
            this.疾病診斷 = new HashSet<疾病診斷>();
            this.病人開藥日期 = new HashSet<病人開藥日期>();
        }
    
        public int fid { get; set; }
        public string fName { get; set; }
        public string fSex { get; set; }
        public string fCheckin { get; set; }
        public string fIdnum { get; set; }
        public string fBednum { get; set; }
        public string fBirthday { get; set; }
        public string fHomeNum { get; set; }
        public string fPhone { get; set; }
        public string fEdu { get; set; }
        public string fMarried { get; set; }
        public string fAddress { get; set; }
        public string fHos { get; set; }
        public string fIDY { get; set; }
        public string fGrant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmergenceCaller> EmergenceCaller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<功能評估> 功能評估 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<疾病診斷> 疾病診斷 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<病人開藥日期> 病人開藥日期 { get; set; }
    }
}
