//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 康家_藥物疾病列表
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGroupActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tGroupActivity()
        {
            this.tGroupActivityClassTheme = new HashSet<tGroupActivityClassTheme>();
            this.tGroupActivityPicAndFiles = new HashSet<tGroupActivityPicAndFiles>();
            this.tPersonalPerformance = new HashSet<tPersonalPerformance>();
            this.tScheduleDetails = new HashSet<tScheduleDetails>();
        }
    
        public Nullable<int> fID { get; set; }
        public Nullable<bool> fDeleteBool { get; set; }
        public int fGroupActivityID { get; set; }
        public string fEventType { get; set; }
        public string fDate { get; set; }
        public string fStartTime { get; set; }
        public string fEndTime { get; set; }
        public string fGroupName { get; set; }
        public string fClassName { get; set; }
        public string fGoal { get; set; }
        public string fLocation { get; set; }
        public int fPeopleCount { get; set; }
        public string fLeader { get; set; }
        public string fRecorder { get; set; }
        public string fProcess { get; set; }
        public string fAchievement { get; set; }
        public string fFillFormStaff { get; set; }
        public string fFillFormDate { get; set; }
    
        public virtual tEventType tEventType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGroupActivityClassTheme> tGroupActivityClassTheme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGroupActivityPicAndFiles> tGroupActivityPicAndFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPersonalPerformance> tPersonalPerformance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tScheduleDetails> tScheduleDetails { get; set; }
    }
}
