//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 康家_藥物疾病列表
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPersonalPerformance
    {
        public int fID { get; set; }
        public string fDeleteBool { get; set; }
        public int fGroupActivityID { get; set; }
        public int fResidentID { get; set; }
        public string fEmotions { get; set; }
        public string fParticipatePersistence { get; set; }
        public string fCooperate { get; set; }
        public string fHumanInteraction { get; set; }
        public string fAttention { get; set; }
        public string fParticipatePerformance { get; set; }
        public string fDepiction { get; set; }
    
        public virtual tGroupActivity tGroupActivity { get; set; }
    }
}
