//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 康家_藥物疾病列表
{
    using System;
    using System.Collections.Generic;
    
    public partial class 功能評估個表
    {
        public int ID_評估表 { get; set; }
        public int f功能評估ID { get; set; }
        public string f評估項目 { get; set; }
        public string f現狀評估 { get; set; }
        public string f問題 { get; set; }
        public string f復健目標 { get; set; }
        public string f復健計畫 { get; set; }
    
        public virtual 功能評估 功能評估 { get; set; }
    }
}
