//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 康家_藥物疾病列表
{
    using System;
    using System.Collections.Generic;
    
    public partial class 功能評估
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 功能評估()
        {
            this.tFunctionBrige = new HashSet<tFunctionBrige>();
            this.功能評估個表 = new HashSet<功能評估個表>();
        }
    
        public int f功能評估ID { get; set; }
        public int fid { get; set; }
        public string f日期 { get; set; }
        public Nullable<decimal> f身高 { get; set; }
        public Nullable<decimal> f體重 { get; set; }
    
        public virtual PatientInfo PatientInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tFunctionBrige> tFunctionBrige { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<功能評估個表> 功能評估個表 { get; set; }
    }
}
