//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 康家_藥物疾病列表
{
    using System;
    using System.Collections.Generic;
    
    public partial class 病人用藥資訊
    {
        public int ID_Patient_Medicine_Info { get; set; }
        public Nullable<int> ID_GetMedicineDate { get; set; }
        public string MedicineChineseName { get; set; }
        public string MedicineUsage { get; set; }
        public string MedicineTakeTime { get; set; }
        public string MedicineDosage { get; set; }
        public string MedicineADDInfo { get; set; }
    
        public virtual 病人開藥日期 病人開藥日期 { get; set; }
    }
}
